#! /bin/sh
#
# Run from the mmj2 top directory.
# Should produce "mmj2.jar".
#
echo "Manifest-Version: 1.0" >MANIFEST.MF
echo "Main-Class: mmj.util.BatchMMJ2" >>MANIFEST.MF
cd src && javac `find . ../lib -name *.java` -d ../classes && \
cd ../classes && \
jar cfm ../mmj2.jar ../MANIFEST.MF \
`find -name "*.class" | sed -e "s/^\.\///"`
